// This file is part of AsmJit project <https://asmjit.com>
//
// See <asmjit/core.h> or LICENSE.md for license and copyright information.
// SPDX-License-Identifier: Zlib

#include "../core/api-build_p.h"
#include "../core/instdb_p.h"
#include "../riscv/riscvinstdb.h"

ASMJIT_BEGIN_SUB_NAMESPACE(riscv)

namespace InstDB {

// The `_opRWInfoTable` is not defined here, because it's complex and is typically
// generated by a script. The indices used here are placeholders that represent
// common operand read/write patterns.
enum OpRWInfoIndex : uint16_t {
  kRW_None = 0,
  kRW_r_r_r,      // rd, rs1, rs2 (R-Type)
  kRW_r_r_imm,    // rd, rs1, imm (I-Type)
  kRW_r_mem,      // rd, mem      (Load)
  kRW_mem_r,      // mem, rs2      (Store)
  kRW_r_r_label,  // rs1, rs2, label (B-Type)
  kRW_r_label,    // rd, label    (J-Type)
  kRW_fence       // fence
};

// A helper to define a R-Type instruction info.
static constexpr InstInfo R(uint32_t opcode, uint32_t funct3, uint32_t funct7, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kR), opcode, funct3, funct7, 0, rwInfoIndex, flags };
}

// A helper to define a I-Type instruction info.
static constexpr InstInfo I(uint32_t opcode, uint32_t funct3, uint32_t shftyp, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kI), opcode, funct3, shftyp, 0, rwInfoIndex, flags };
}

// A helper to define a S-Type instruction info.
static constexpr InstInfo S(uint32_t opcode, uint32_t funct3, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kS), opcode, funct3, 0, 0, rwInfoIndex, flags };
}

// A helper to define a B-Type instruction info.
static constexpr InstInfo B(uint32_t opcode, uint32_t funct3, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kB), opcode, funct3, 0, 0, rwInfoIndex, static_cast<uint16_t>(flags | InstFlags::kIsBranch) };
}

// A helper to define a U-Type instruction info.
static constexpr InstInfo U(uint32_t opcode, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kU), opcode, 0, 0, 0, rwInfoIndex, flags };
}

// A helper to define a J-Type instruction info.
static constexpr InstInfo J(uint32_t opcode, uint16_t rwInfoIndex, uint16_t flags = 0) noexcept {
  return InstInfo { uint32_t(EncodingType::kJ), opcode, 0, 0, 0, rwInfoIndex, static_cast<uint16_t>(flags | InstFlags::kIsJump) };
}

const InstInfo _instInfoTable[] = {
  { (uint32_t)EncodingType::kNone, 0, 0, kRW_None, 0 }, // kIdNone

  // RV32I/RV64I Base Instruction Set
  // R-Type
  R(0b0110011, 0b000, 0b0000000, kRW_r_r_r), // kIdAdd
  R(0b0111011, 0b000, 0b0000000, kRW_r_r_r), // kIdAddw
  R(0b0110011, 0b000, 0b0100000, kRW_r_r_r), // kIdSub
  R(0b0111011, 0b000, 0b0100000, kRW_r_r_r), // kIdSubw
  R(0b0110011, 0b001, 0b0000000, kRW_r_r_r), // kIdSll
  R(0b0111011, 0b001, 0b0000000, kRW_r_r_r), // kIdSllw
  R(0b0110011, 0b101, 0b0000000, kRW_r_r_r), // kIdSrl
  R(0b0111011, 0b101, 0b0000000, kRW_r_r_r), // kIdSrlw
  R(0b0110011, 0b101, 0b0100000, kRW_r_r_r), // kIdSra
  R(0b0111011, 0b101, 0b0100000, kRW_r_r_r), // kIdSraw
  R(0b0110011, 0b010, 0b0000000, kRW_r_r_r), // kIdSlt
  R(0b0110011, 0b011, 0b0000000, kRW_r_r_r), // kIdSltu
  R(0b0110011, 0b111, 0b0000000, kRW_r_r_r), // kIdAnd
  R(0b0110011, 0b110, 0b0000000, kRW_r_r_r), // kIdOr
  R(0b0110011, 0b100, 0b0000000, kRW_r_r_r), // kIdXor
  // I-Type
  I(0b0010011, 0b000, 0b0000000, kRW_r_r_imm), // kIdAddi
  I(0b0011011, 0b000, 0b0000000, kRW_r_r_imm), // kIdAddiw
  I(0b0010011, 0b010, 0b0000000, kRW_r_r_imm), // kIdSlti
  I(0b0010011, 0b011, 0b0000000, kRW_r_r_imm), // kIdSltiu
  I(0b0010011, 0b111, 0b0000000, kRW_r_r_imm), // kIdAndi
  I(0b0010011, 0b110, 0b0000000, kRW_r_r_imm), // kIdOri
  I(0b0010011, 0b100, 0b0000000, kRW_r_r_imm), // kIdXOri
  // Shift
  I(0b0010011, 0b001, 0b0000000, kRW_r_r_imm), // kIdSlli
  I(0b0011011, 0b001, 0b0000000, kRW_r_r_imm), // kIdSlliw
  I(0b0010011, 0b101, 0b0000000, kRW_r_r_imm), // kIdSrli
  I(0b0011011, 0b101, 0b0000000, kRW_r_r_imm), // kIdSrliw
  I(0b0010011, 0b101, 0b0100000, kRW_r_r_imm), // kIdSrai
  I(0b0011011, 0b101, 0b0100000, kRW_r_r_imm), // kIdSraiw
  I(0b1100111, 0b000, 0b0000000, kRW_r_r_imm), // kIdJalr
  // Load
  I(0b0000011, 0b000, 0b0000000, kRW_r_mem), // kIdLb
  I(0b0000011, 0b001, 0b0000000, kRW_r_mem), // kIdLh
  I(0b0000011, 0b010, 0b0000000, kRW_r_mem), // kIdLw
  I(0b0000011, 0b100, 0b0000000, kRW_r_mem), // kIdLbu
  I(0b0000011, 0b101, 0b0000000, kRW_r_mem), // kIdLhu
  I(0b0000011, 0b110, 0b0000000, kRW_r_mem), // kIdLwu
  I(0b0000011, 0b011, 0b0000000, kRW_r_mem), // kIdLd
  // S-Type
  S(0b0100011, 0b000, kRW_mem_r), // kIdSb
  S(0b0100011, 0b001, kRW_mem_r), // kIdSh
  S(0b0100011, 0b010, kRW_mem_r), // kIdSw
  S(0b0100011, 0b011, kRW_mem_r), // kIdSd
  // B-Type
  B(0b1100011, 0b000, kRW_r_r_label), // kIdBeq
  B(0b1100011, 0b001, kRW_r_r_label), // kIdBne
  B(0b1100011, 0b100, kRW_r_r_label), // kIdBlt
  B(0b1100011, 0b101, kRW_r_r_label), // kIdBge
  B(0b1100011, 0b110, kRW_r_r_label), // kIdBltu
  B(0b1100011, 0b111, kRW_r_r_label), // kIdBgeu
  // U-Type
  U(0b0110111, kRW_None), // kIdLui
  U(0b0010111, kRW_None), // kIdAuipc
  // J-Type
  J(0b1101111, kRW_r_label), // kIdJal
  // Others
  I(0b0010011, 0b000, 0b0000000, kRW_None), // kIdNop
  I(0b0001111, 0b000, 0b0000000, kRW_fence), // kIdFence
};
// ${InstInfo:End}
}
ASMJIT_END_SUB_NAMESPACE